#!/bin/bash

set -e

cd /opt/

## Extract the package
tar xf /opt/ideaIU-2023.2.tar.gz

## Rename the directory
mv /opt/idea-IU-* /opt/intellij-idea-ultimate

## Remove  the tar.gz package
rm /opt/ideaIU-2023.2.tar.gz

## Install the .desktop file, if necessary
if [ -x "/usr/bin/desktop-file-install" ]; then
    desktop-file-install /usr/share/applications/intellij-idea-ultimate.desktop
fi

##DEBHELPER##
